// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydlwaygkalhvpixqkiwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbHdheWdrYWxodnBpeHFraXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzE1MDcsImV4cCI6MjA2NTUwNzUwN30.sL31vq1zAIk5FMrueY6hoQPG3FBOrULlFdvJR9c2xqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);